name: verta

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: verta_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - verta_rabbit_data:/var/lib/rabbitmq
  db:
    image: postgres:17
    container_name: verta_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: verta_db
    ports:
      - "5432:5432"
    volumes:
      - verta_postgres_data:/var/lib/postgresql/data

  verta-api:
    build:
      context: ../..
      dockerfile: infra/docker/backend.Dockerfile
    container_name: verta_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=verta_db;Username=admin;Password=password123
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ASPNETCORE_ENVIRONMENT=Development

  pgadmin:
    image: dpage/pgadmin4
    container_name: verta_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@verta.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  verta_postgres_data:
  verta_rabbit_data:
